### ISSUE TITLE
Empty `top_level.txt`, unable to import

### ISSUE THREAD

**Issue by bmeares** [COUR4G3/requests-scram#1]
Installing this package with `pip` does not download the module source to `~/.local/lib/python3.12/site-packages` (downloading the tarball directly from [PyPI](https://pypi.org/project/requests-scram/#files) includes the module), so I believe something may be misconfigured in `pyproject.toml` relating to `setuptools`. Nothing jumps out to me directly, though I may open a PR later on if I am able to figure out what's going on (I'm still in the process of breaking away from `setup.py` and migrating to `pyproject.toml`).

I hope this was helpful ― and I'm excited to use this package, thank you for putting it together!

Edit: Tested with Python 3.10 and 3.12 on Fedora, `pip` v23.3.2.

**Comment by COUR4G3** [comment]
@bmeares, thanks for spotting this, it was my first time using pyproject.toml for a single-file module. I have fixed this and uploaded a new release to PyPi.

And let me know how it works. I've only ever tested it with my own small [flask-scram](https://github.com/COUR4G3/flask-scram) examples - which I might need to go fix that release too 🤣
